---
services:
  terragrunt:
    image:        aaheiev/opentofu:1.8.1-1
    platform:     linux/amd64
    stdin_open:   true
    tty:          true
    build:
      dockerfile: Dockerfile
    environment:
      AWS_DEFAULT_REGION: us-west-2
    env_file:
      - ./.env
    volumes:
      - .:/workspace
