name: OpenTofu image build and publish

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - github-actions

#  pull_request:
#    branches: [ "main" ]
#
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set build version
        run: |
          OPENTOFU_VERSION=$(cat .opentofu.version)
          VERSION="${OPENTOFU_VERSION}-${{ github.run_number }}"
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV
          echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo $VERSION)"

      - name: Show build version
        run: |
          echo "VERSION=${{ env.VERSION }}"

#      - name: "Build image with tag ${{ env.COMMIT_TAG }}"
#        uses: aevea/action-kaniko@v0.11.0
#        with:
#          image: ${{ env.IMAGE_REPO_NAME }}
#          registry: ghcr.io
#          password: ${{ secrets.GITHUB_TOKEN }}
#          build_file: ${{ env.DOCKER_PATH }}/Dockerfile
#          tag: ${{ env.COMMIT_TAG }}
#          tag_with_latest: false
#          cache: true
#          cache_registry: ${{ env.IMAGE_REPO_NAME }}-cache
#          extra_args: --use-new-run --build-arg TERRAFORM_VERSION=${{ env.TERRAFORM_VERSION }}
